# Generated by Django 3.2.9 on 2021-11-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0002_alter_reply_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment_id',
        ),
    ]
