# Generated by Django 3.2.9 on 2021-11-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_comment_replies'),
        ('replies', '0004_reply_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
