# Generated by Django 3.2.9 on 2021-11-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0006_auto_20211130_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
    ]
