# Generated by Django 3.2.9 on 2021-11-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0003_remove_reply_comment_id'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='replies.reply'),
        ),
    ]
